name: Guest Registration
on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  process-guest:
    runs-on: ubuntu-latest
    steps:
      - name: Close the issue
        uses: actions/github-script@v6
        env:
          TOKEN: ${{ secrets.GUEST_REG_TOKEN }}
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              state: 'closed'
            })
